# FORMATION DOCKER DEPLOIEMENT JOOMLA
formatdockdb:
  hostname: formatdockdb
  image: sylviefiat/alpine-mysql
  volumes:
    - ./formatdockdb_data:/var/lib/mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_USER=docker
    - MYSQL_USER_PWD=docker
    - MYSQL_ROOT_PWD=docker

formatdockgis:
  image: sylviefiat/docker-geoserver
  hostname: formatdockgis
  volumes:
    - ./formatdockgis_data/data_dir:/opt/geoserver/data_dir
  ports:
    - "8080:8080"
  links:
    - formatdockdb:formatdockdb

formatdock:
  image: joomla
  hostname: formatdock
  ports:
    - 80:80
  volumes:
    - ./formatdock_data/app:/app
  environment:
    - JOOMLA_DB_USER=docker
    - JOOMLA_DB_PASSWORD=docker
    - JOOMLA_DB_NAME=oreanet
  links:
    - formatdockdb:formatdockdb
    - formatdockgis:formatdockgis


