# OREANET NEW CALEDONIA WEBSITE
oreanetdb:
  hostname: oreanetdb
  image: sylviefiat/alpine-mysql
  volumes:
    - ./oreanetdb_data:/var/lib/mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_USER=docker
    - MYSQL_USER_PWD=docker
    - MYSQL_ROOT_PWD=docker

oreanetgis:
  image: sylviefiat/docker-geoserver
  hostname: oreanetgis
  volumes:
    - ./oreanetgis_data/data_dir:/opt/geoserver/data_dir
  ports:
    - "8080:8080"
  links:
    - oreanetdb:oreanetdb

oreanet:
#  image: sylviefiat/joomla-cot:2.0
#  build:
#    context: ./oreanet_data
#  command: /run.sh
  image: joomla
  hostname: oreanet
  ports:
    - 80:80
#    - 25:25
  volumes:
    - ./oreanet_data/app:/app
  environment:
    - JOOMLA_DB_HOST=oreanetdb:3306
    - JOOMLA_DB_USER=docker
    - JOOMLA_DB_PASSWORD=docker
    - JOOMLA_DB_NAME=oreanet
  links:
    - oreanetdb:oreanetdb
    - oreanetgis:oreanetgis

#oreanet-fj:
#  image: sylviefiat/joomla-cot
#  command: /run.sh
#  hostname: oreanet-fj
#  ports:
#    - 84:80
#    - 26:25
#  volumes:
#    - ./oreanet-fj_data/app:/app
#  links:
#    - oreanetdb:oreanetdb
#    - oreanetgis:oreanetgis

 #oreanet-vt:
 # image: sylviefiat/vcot-monitoring
 # hostname: oreanet-vt
 # ports:
 #   - 85:80
 #   - 27:25
 # volumes:
 #   - ./oreanet-vt_data/app:/app
 # links:
 #   - oreanetgis:oreanetgis


