# OREANET NEW CALEDONIA WEBSITE
oreanetdb:
  hostname: oreanetdb
  image: sylviefiat/alpine-mysql
  volumes:
    - ./oreanetdb_data:/var/lib/mysql
  ports:
    - "3307:3306"
  environment:
    - MYSQL_USER=docker
    - MYSQL_USER_PWD=docker
    - MYSQL_ROOT_PWD=docker

oreanetgis:
  image: sylviefiat/docker-geoserver
  hostname: oreanetgis
  volumes:
    - ./oreanetgis_data/data_dir:/opt/geoserver/data_dir
  ports:
    - "8082:8080"
  links:
    - oreanetdb:oreanetdb

oreanet:
  image: sylviefiat/joomla-cot
  command: /run.sh
  hostname: oreanet
  ports:
    - 82:80
    - 25:25
  volumes:
    - ./oreanet_data/app:/app
  links:
    - oreanetdb:oreanetdb
    - oreanetgis:oreanetgis

oreanet-fj:
  image: sylviefiat/joomla-cot
  command: /run.sh
  hostname: oreanet-fj
  ports:
    - 84:80
    - 26:25
  volumes:
    - ./oreanet-fj_data/app:/app
  links:
    - oreanetdb:oreanetdb
    - oreanetgis:oreanetgis

 #oreanet-vt:
 # image: sylviefiat/vcot-monitoring
 # hostname: oreanet-vt
 # ports:
 #   - 85:80
 #   - 27:25
 # volumes:
 #   - ./oreanet-vt_data/app:/app
 # links:
 #   - oreanetgis:oreanetgis


